export enum userConstants {
    GET_ALL_USERS_SUCCESS = "GET_ALL_USERS_SUCCESS",
    USER_CREATE_SUCCESS = 'USER_CREATE_SUCCESS',
    USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS',
    USER_DELETE_SUCCESS = 'USER_DELETE_SUCCESS'
}