export enum projectConstants {
  GET_ALL_PROJECT_SUCCESS = 'GET_ALL_PROJECT_SUCCESS',
  GET_ALL_PROJECT_LOADING = ' GET_ALL_PROJECT_LOADING',
  GET_ALL_PROJECT_FAILED = 'GET_ALL_PROJECT_FAILED',
  PROJECT_CREATE_SUCCESS = 'PROJECT_CREATE_SUCCESS',
  PROJECT_CREATE_LOADING = 'PROJECT_CREATE_LOADING',
  PROJECT_CREATE_FAILED = 'PROJECT_CREATE_FAILED',
  PROJECT_DELETE_SUCCESS = 'PROJECT_DELETE_SUCCESS',
  PROJECT_DELETE_LOADING = 'PROJECT_DELETE_LOADING',
  PROJECT_DELETE_FAILED = 'PROJECT_DELETE_FAILED'
}
